### ISSUE TITLE
I tried to run with "-w -id 1500" but it still close the toast automatically

### ISSUE THREAD

**Issue by rongsheng** [Snorenotify/Snoretoast#5]
it says "The toast has timed out" after a few seconds running the command

toast -w -id 1501 -t "Restarting" -m "Site: Website is currently being restarted... " -p "C:\xxx\restart.png"

**Comment by TheOneRing** [comment]
Hi where you trying to create a sticky notification?

    [-w]                    | Wait for toast to expire or activate.

Sticky notifications are not supported [see MSDN](https://msdn.microsoft.com/en-us/library/windows/apps/hh779727.aspx) but I could try to add support for "Long-duration toast"
