### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by Big--Mike** [Snorenotify/Snoretoast#7]
Hi, 

it would be nice if you could enhance Snotetoast to display different background colors. Maybe by RGB color code

**Comment by TheOneRing** [comment]
The colour is selected by the System. On Windows 8 it is the mean colour from the icon registered to the app ID see readme. And an example of how to setup the app id in https://github.com/Snorenotify/Snorenotify/wiki/Windows-Toast-Notification
