### ISSUE TITLE
Also make a "non console application"

### ISSUE THREAD

**Issue by Big--Mike** [Snorenotify/Snoretoast#8]
Hi,

if I trigger Snoretoast from a Windows GUI application, a console window is displayed for short time. It would be nice to have a version which doesn't display this window.

**Comment by TheOneRing** [comment]
You have to change the way you call Snoretoast.
Depending on how it is done the console window is displayed or not. This is nothing that can be changed in Snoretoast.

**Comment by Big--Mike** [comment]
Actually I thought, it's a matter of compiling the application as "Console Application" or "Windows Application", as double clicking on Snoretoast.exe will create a console window, while double clicking e.g. on explorer.exe does not. So I thought, providing a second non console executable would do the trick.
It's a pitty, I can't do anything about calling the application. FYI, I try to use Snoretoast combined with the extension "Mailbox Alert" to get Toast notifications from Thunderbird if a new mail is received.

**Comment by TheOneRing** [comment]
Thanks for the input.
SnoreToast is now a Gui application which attaches to the console if available.
Please try https://github.com/Snorenotify/Snoretoast/releases/tag/v0.5.0

**Comment by TheOneRing** [comment]
I now create to applications a standard cmd version and a GUI version for scenarios like yours.

**Comment by Big--Mike** [comment]
Thank you, that's really cool :)
